version: "3"

services:
  app:
    container_name: backend
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - 4000:3000
    restart: always
    environment:
      - MONGO_URI=mongodb://root:pass12345@mongodb:27017/ipinfo

  mongodb:
    container_name: database
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    restart: always
    ports:
      - 27017:27017